// tslint:disable
/**
 * mediaTrack
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserVO } from './user';

/**
 * 
 * @export
 * @interface CommentVO
 */
export interface CommentVO {
    /**
     * ID
     * @type {string}
     * @memberof CommentVO
     */
    id: number;
    /**
     * 媒体的id
     * @type {string}
     * @memberof CommentVO
     */
    mediaId: number;
    /**
     * 
     * @type {UserVO}
     * @memberof CommentVO
     */
    user: UserVO;
    /**
     * 评论
     * @type {string}
     * @memberof CommentVO
     */
    content: string;
    /**
     * 视频时间戳
     * @type {number}
     * @memberof CommentVO
     */
    timestamp?: number;
    /**
     * 是否被编辑
     * @type {boolean}
     * @memberof CommentVO
     */
    isEdited: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof CommentVO
     */
    imageUrls: Array<string>;
    /**
     * 创建时间
     * @type {string}
     * @memberof CommentVO
     */
    createdAt: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof CommentVO
     */
    updatedAt?: string;
    /**
     * 删除时间
     * @type {string}
     * @memberof CommentVO
     */
    deletedAt?: string;
}


