// tslint:disable
/**
 * mediaTrack
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject2
 */
export interface InlineObject2 {
    /**
     * name
     * @type {string}
     * @memberof InlineObject2
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject2
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject2
     */
    descript?: string;
}


