// tslint:disable
/**
 * mediaTrack
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Media } from './media';

/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * 200 默认成功
     * @type {number}
     * @memberof InlineResponse2002
     */
    code: number;
    /**
     * 错误说明
     * @type {string}
     * @memberof InlineResponse2002
     */
    msg: string;
    /**
     * 
     * @type {Array<Media>}
     * @memberof InlineResponse2002
     */
    data: Array<Media>;
}


