// tslint:disable
/**
 * mediaTrack
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 媒体的id
     * @type {string}
     * @memberof InlineObject
     */
    mediaId: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    userId: string;
    /**
     * 评论
     * @type {string}
     * @memberof InlineObject
     */
    content: string;
    /**
     * 视频时间戳
     * @type {number}
     * @memberof InlineObject
     */
    timestamp: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject
     */
    imageUrls?: Array<string>;
}


