// tslint:disable
/**
 * mediaTrack
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { User } from './user';

/**
 * 
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
    /**
     * 200 默认成功
     * @type {number}
     * @memberof InlineResponse2004
     */
    code: number;
    /**
     * 错误说明
     * @type {string}
     * @memberof InlineResponse2004
     */
    msg: string;
    /**
     * 
     * @type {User}
     * @memberof InlineResponse2004
     */
    data: User;
}


