// tslint:disable
/**
 * mediaTrack
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserVO
 */
export interface UserVO {
    /**
     * ID
     * @type {number}
     * @memberof UserVO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserVO
     */
    account: string;
    /**
     * name
     * @type {string}
     * @memberof UserVO
     */
    name: string;
    /**
     * 头像地址
     * @type {string}
     * @memberof UserVO
     */
    avatarUrl: string;
    /**
     * 创建时间
     * @type {string}
     * @memberof UserVO
     */
    createdAt: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof UserVO
     */
    updatedAt: string;
    /**
     * 删除
     * @type {string}
     * @memberof UserVO
     */
    deletedAt: string;
}


