// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username  string         `gorm:"column:username;not null;comment:用户名" json:"username"`   // 用户名
	Password  string         `gorm:"column:password;not null;comment:密码" json:"password"`    // 密码
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间，软删除标记" json:"deleted_at"` // 删除时间，软删除标记
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
