// tslint:disable
/**
 * mediaTrack
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Base
 */
export interface Base {
    /**
     * 创建时间
     * @type {string}
     * @memberof Base
     */
    createdAt: string;
    /**
     * 更新时间
     * @type {string}
     * @memberof Base
     */
    updatedAt: string;
    /**
     * 删除时间
     * @type {string}
     * @memberof Base
     */
    deletedAt: string;
}


