// tslint:disable
/**
 * mediaTrack
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { InlineResponse200 } from '../models';
/**
 * MediaTrackApi - axios parameter creator
 * @export
 */
export const MediaTrackApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取媒体评论
         * @param {string} mediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1GetCommentListMediaIdGet: async (mediaId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'mediaId' is not null or undefined
            if (mediaId === null || mediaId === undefined) {
                throw new RequiredError('mediaId','Required parameter mediaId was null or undefined when calling apiV1GetCommentListMediaIdGet.');
            }
            const localVarPath = `/api/v1/getCommentList/{mediaId}`
                .replace(`{${"mediaId"}}`, encodeURIComponent(String(mediaId)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MediaTrackApi - functional programming interface
 * @export
 */
export const MediaTrackApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取媒体评论
         * @param {string} mediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1GetCommentListMediaIdGet(mediaId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await MediaTrackApiAxiosParamCreator(configuration).apiV1GetCommentListMediaIdGet(mediaId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * MediaTrackApi - factory interface
 * @export
 */
export const MediaTrackApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 获取媒体评论
         * @param {string} mediaId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1GetCommentListMediaIdGet(mediaId: string, options?: any): AxiosPromise<InlineResponse200> {
            return MediaTrackApiFp(configuration).apiV1GetCommentListMediaIdGet(mediaId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MediaTrackApi - object-oriented interface
 * @export
 * @class MediaTrackApi
 * @extends {BaseAPI}
 */
export class MediaTrackApi extends BaseAPI {
    /**
     * 
     * @summary 获取媒体评论
     * @param {string} mediaId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MediaTrackApi
     */
    public apiV1GetCommentListMediaIdGet(mediaId: string, options?: any) {
        return MediaTrackApiFp(this.configuration).apiV1GetCommentListMediaIdGet(mediaId, options).then((request) => request(this.axios, this.basePath));
    }

}
